/**
 * GLITCH MATRIX — Question Data File
 * ====================================
 * Edit this file to change questions without touching game logic.
 * Each module has a `type` that determines which UI component renders it.
 *
 * Module Types:
 *  - spot_the_glitch   : Click the odd item in a grid
 *  - emoji_decode      : Decode emoji sequence to a word
 *  - unscramble        : Drag/click letters to form a word
 *  - odd_one_out       : Pick the item that doesn't belong (8s timer)
 *  - tech_riddle       : 4-option multiple choice riddle
 *  - tech_sequence     : Fill in the missing number in a sequence
 *  - guess_technology  : 3-clue progressive reveal
 */

export const MODULES = [
  // ─── MODULE 1: SPOT THE GLITCH ──────────────────────────────────────────────
  {
    id: 1,
    title: "SPOT THE GLITCH",
    subtitle: "Logo visual anomaly detected. Locate the corrupted feature and eliminate it.",
    icon: "🔍",
    type: "spot_the_glitch",
    color: "#00f0ff",
    questions: [
      {
        id: 1,
        brand: "NVIDIA",
        difficulty: "Easy",
        prompt: "Identify the anomaly in the NVIDIA visual identity:",
        prompt_instructions: "NVIDIA logo: Render the bright green curved spiral eye icon. The error is that the inner pupil of the eye is shaped like a red hexagon instead of a black circle.",
        glitch_type: "Shape/Color Shift",
        explanation: "The NVIDIA 'eye' icon’s pupil is black; it should not be a red hexagon.",
        emoji_hint: "👁️",
        click_hit_box_normalized: { top: 0.40, left: 0.45, bottom: 0.60, right: 0.55 },
        image_asset_reference: "logo_nvidia",
        successMsg: "NVIDIA GLITCH ELIMINATED ✓",
      },
      {
        id: 2,
        brand: "Snapchat",
        difficulty: "Easy",
        prompt: "Identify the anomaly in the Snapchat visual identity:",
        prompt_instructions: "Snapchat logo: Render the classic white 'Ghostface Chillah' ghost icon on a pure bright yellow background. The error is that the ghost is wearing a tiny red bowtie.",
        glitch_type: "Asset Addition",
        explanation: "The Snapchat ghost does not wear a red bowtie.",
        emoji_hint: "👻",
        click_hit_box_normalized: { top: 0.70, left: 0.40, bottom: 0.85, right: 0.60 },
        image_asset_reference: "logo_snapchat",
        successMsg: "SNAPCHAT GLITCH ELIMINATED ✓",
      },
      {
        id: 3,
        brand: "OpenAI / ChatGPT",
        difficulty: "Medium",
        prompt: "Identify the anomaly in the OpenAI/ChatGPT visual identity:",
        prompt_instructions: "OpenAI/ChatGPT logo: Render the dark teal geometric rosette blossom. The error is that the two spiral lines in the bottom-left quadrant fail to intersect, leaving a small gap.",
        glitch_type: "Geometry Error",
        explanation: "The interlocking geometry of the OpenAI logo is seamless; it must connect.",
        emoji_hint: "🤖",
        click_hit_box_normalized: { top: 0.55, left: 0.35, bottom: 0.75, right: 0.55 },
        image_asset_reference: "logo_openai",
        successMsg: "OPENAI GLITCH ELIMINATED ✓",
      },
      {
        id: 4,
        brand: "Android",
        difficulty: "Easy",
        prompt: "Identify the anomaly in the Android visual identity:",
        prompt_instructions: "Google Android logo: Render the neon green bugdroid robot head. The error is that the right-side antenna is angled downward at 45 degrees, while the left antenna is correct (pointing up).",
        glitch_type: "Position Error",
        explanation: "Both of the Android robot's antennae point upward at parallel angles.",
        emoji_hint: "🐛",
        click_hit_box_normalized: { top: 0.10, left: 0.60, bottom: 0.30, right: 0.75 },
        image_asset_reference: "logo_android",
        successMsg: "ANDROID GLITCH ELIMINATED ✓",
      },
      {
        id: 5,
        brand: "Xbox",
        difficulty: "Medium",
        prompt: "Identify the anomaly in the Xbox visual identity:",
        prompt_instructions: "Microsoft Xbox logo: Render the sphere showing the classic embedded 'X'. The error is that the 'X' is colored glowing blue instead of the correct glowing green.",
        glitch_type: "Color Swap",
        explanation: "The Xbox icon's internal 'X' glows with signature green light, not blue.",
        emoji_hint: "🎮",
        click_hit_box_normalized: { top: 0.20, left: 0.30, bottom: 0.80, right: 0.70 },
        image_asset_reference: "logo_xbox",
        successMsg: "XBOX GLITCH ELIMINATED ✓",
      },
      {
        id: 6,
        brand: "Python",
        difficulty: "Hard",
        prompt: "Identify the anomaly in the Python visual identity:",
        prompt_instructions: "Python logo: Render the blue and yellow interlocking snake heads. The error is that the blue snake head’s eye dot is missing entirely.",
        glitch_type: "Asset Removal",
        explanation: "Both snake heads in the Python logo have a single round dot eye.",
        emoji_hint: "🐍",
        click_hit_box_normalized: { top: 0.20, left: 0.25, bottom: 0.40, right: 0.35 },
        image_asset_reference: "logo_python",
        successMsg: "PYTHON GLITCH ELIMINATED ✓",
      },
      {
        id: 7,
        brand: "Discord",
        difficulty: "Easy",
        prompt: "Identify the anomaly in the Discord visual identity:",
        prompt_instructions: "Discord logo: Render the white 'Clyde' controller/robot mascot on the blurple background. The error is that the small smile on the mascot is upside down (a frown).",
        glitch_type: "Feature Inversion",
        explanation: "The Discord mascot, Clyde, has a cheerful smile, not a frown.",
        emoji_hint: "🎧",
        click_hit_box_normalized: { top: 0.65, left: 0.40, bottom: 0.80, right: 0.60 },
        image_asset_reference: "logo_discord",
        successMsg: "DISCORD GLITCH ELIMINATED ✓",
      },
      {
        id: 8,
        brand: "Spotify",
        difficulty: "Hard",
        prompt: "Identify the anomaly in the Spotify visual identity:",
        prompt_instructions: "Spotify logo: Render the neon green circle containing the black sound wave arcs. The error is that there are four concentric black arcs instead of the correct three.",
        glitch_type: "Frequency/Count Error",
        explanation: "The Spotify 'Wi-Fi' style sound waves are composed of exactly three arcs.",
        emoji_hint: "🎵",
        click_hit_box_normalized: { top: 0.35, left: 0.40, bottom: 0.65, right: 0.60 },
        image_asset_reference: "logo_spotify",
        successMsg: "SPOTIFY GLITCH ELIMINATED ✓",
      },
      {
        id: 9,
        brand: "GitHub",
        difficulty: "Medium",
        prompt: "Identify the anomaly in the GitHub visual identity:",
        prompt_instructions: "GitHub logo: Render the silhouette of the 'Octocat' (cat-octopus hybrid) on a white background. The error is that the central tentacle (the 5th one) is clearly missing.",
        glitch_type: "Asset Removal",
        explanation: "The GitHub Octocat silhouette should have exactly five visible limbs/tentacles.",
        emoji_hint: "🐙",
        click_hit_box_normalized: { top: 0.75, left: 0.45, bottom: 0.90, right: 0.55 },
        image_asset_reference: "logo_github",
        successMsg: "GITHUB GLITCH ELIMINATED ✓",
      },
      {
        id: 10,
        brand: "Linux",
        difficulty: "Easy",
        prompt: "Identify the anomaly in the Linux visual identity:",
        prompt_instructions: "Linux logo: Render the friendly penguin mascot, Tux. The error is that Tux is missing its signature orange webbed left foot (only the right foot is present).",
        glitch_type: "Asset Removal",
        explanation: "Tux the penguin always has two orange webbed feet.",
        emoji_hint: "🐧",
        click_hit_box_normalized: { top: 0.75, left: 0.30, bottom: 0.95, right: 0.45 },
        image_asset_reference: "logo_linux",
        successMsg: "LINUX GLITCH ELIMINATED ✓",
      },
      {
        id: 11,
        brand: "VS Code",
        difficulty: "Medium",
        prompt: "Identify the anomaly in the Microsoft VS Code visual identity:",
        prompt_instructions: "Microsoft Visual Studio Code logo: Render the interlocking blue origami ribbons forming an infinity shape. The error is that the very center fold where the ribbons meet is colored glowing purple instead of matching blue.",
        glitch_type: "Color Swap",
        explanation: "The internal fold of the VS Code logo is monochromatic blue; it does not contain purple.",
        emoji_hint: "💻",
        click_hit_box_normalized: { top: 0.45, left: 0.45, bottom: 0.55, right: 0.55 },
        image_asset_reference: "logo_vscode",
        successMsg: "VS CODE GLITCH ELIMINATED ✓",
      },
      {
        id: 12,
        brand: "Docker",
        difficulty: "Hard",
        prompt: "Identify the anomaly in the Docker visual identity:",
        prompt_instructions: "Docker logo: Render the friendly blue whale mascot carrying containers. The error is that the topmost blue cargo container (top-center) has the Microsoft Windows 'window' flag logo printed on it, instead of being blank.",
        glitch_type: "Asset Addition/Branding",
        explanation: "Docker containers in the logo are generic blue boxes; they do not carry the Windows logo.",
        emoji_hint: "🐳",
        click_hit_box_normalized: { top: 0.35, left: 0.45, bottom: 0.45, right: 0.55 },
        image_asset_reference: "logo_docker",
        successMsg: "DOCKER GLITCH ELIMINATED ✓",
      },
      {
        id: 13,
        brand: "Bluetooth",
        difficulty: "Hard",
        prompt: "Identify the anomaly in the Bluetooth visual identity:",
        prompt_instructions: "Bluetooth Alliance logo: Render the royal blue oval containing the white Runic B symbol (a combination of Hagalaz and Berkanan runes). The error is that the diagonal cross-line that should go through the H-shape from top-right to bottom-left is missing, creating a closed loop.",
        glitch_type: "Geometry Error",
        explanation: "The Bluetooth bindrune is an open geometric shape; it should not have a closed loop.",
        emoji_hint: "📶",
        click_hit_box_normalized: { top: 0.40, left: 0.45, bottom: 0.60, right: 0.55 },
        image_asset_reference: "logo_bluetooth",
        successMsg: "BLUETOOTH GLITCH ELIMINATED ✓",
      },
      {
        id: 14,
        brand: "Steam",
        difficulty: "Medium",
        prompt: "Identify the anomaly in the Valve Steam visual identity:",
        prompt_instructions: "Valve Steam logo: Render the dark gray mechanical locomotive crank arm mechanism. The error is that the three small circular rivets that secure the joint are colored neon red.",
        glitch_type: "Color Swap",
        explanation: "The rivets on the Steam crank are steel gray; they are not colored neon red.",
        emoji_hint: "🕹️",
        click_hit_box_normalized: { top: 0.45, left: 0.45, bottom: 0.55, right: 0.55 },
        image_asset_reference: "logo_steam",
        successMsg: "STEAM GLITCH ELIMINATED ✓",
      },
      {
        id: 15,
        brand: "Wi-Fi",
        difficulty: "Easy",
        prompt: "Identify the anomaly in the Wi-Fi Alliance visual identity:",
        prompt_instructions: "Wi-Fi Alliance logo: Render the black-and-white yin-yang symbol made of curved radio signal waves. The error is that the white wave on the black background is actually the Bluetooth 'B' rune silhouette.",
        glitch_type: "Shape Inversion",
        explanation: "The Wi-Fi logo uses only simple signal arcs, not other brand logos like Bluetooth.",
        emoji_hint: "📡",
        click_hit_box_normalized: { top: 0.20, left: 0.55, bottom: 0.80, right: 0.85 },
        image_asset_reference: "logo_wifi",
        successMsg: "WI-FI GLITCH ELIMINATED ✓",
      },
    ],
  },

  // ─── MODULE 2: EMOJI DECODE ──────────────────────────────────────────────────
  {
    id: 2,
    title: "EMOJI DECODE",
    subtitle: "Encrypted transmissions detected. Decode the signal.",
    icon: "😀",
    type: "emoji_decode",
    color: "#ff00aa",
    questions: [
      {
        id: "m2q1",
        prompt: "Decrypt this transmission:",
        hint: "Two popular programming languages paired with coding.",
        emojis: ["🐍", "💻", "☕"],
        answer: "Python & Java",
        options: ["Java & Go", "Python & Java", "Rust & C++", "Ruby & Kotlin"],
        successMsg: "PYTHON & JAVA COMPILED ✓",
      },
      {
        id: "m2q2",
        prompt: "Decrypt this transmission:",
        hint: "A decentralized, distributed digital ledger technology.",
        emojis: ["🧱", "🧱", "⛓️"],
        answer: "Blockchain",
        options: ["Cloud Storage", "Blockchain", "VPN Tunnel", "Data Warehouse"],
        successMsg: "BLOCKCHAIN BLOCK MINED ✓",
      },
      {
        id: "m2q3",
        prompt: "Decrypt this transmission:",
        hint: "Network security system that monitors and filters incoming/outgoing network traffic.",
        emojis: ["🔥", "🧱"],
        answer: "Firewall",
        options: ["Firewall", "Hotspot", "BrickOS", "Antivirus"],
        successMsg: "FIREWALL RULES ENGAGED ✓",
      },
      {
        id: "m2q4",
        prompt: "Decrypt this transmission:",
        hint: "Transferring local files to an off-site remote server over the internet.",
        emojis: ["☁️", "💾", "⬆️"],
        answer: "Cloud Upload",
        options: ["Disk Defrag", "Local Backup", "Cloud Upload", "Cache Flush"],
        successMsg: "CLOUD UPLOAD COMPLETE ✓",
      },
      {
        id: "m2q5",
        prompt: "Decrypt this transmission:",
        hint: "Short-range wireless standard used to connect mice, keyboards, and headphones.",
        emojis: ["🦷", "🔵"],
        answer: "Bluetooth",
        options: ["Wi-Fi Direct", "Bluetooth", "NFC", "Zigbee"],
        successMsg: "BLUETOOTH PAIRING SECURED ✓",
      },
      {
        id: "m2q6",
        prompt: "Decrypt this transmission:",
        hint: "The process of locating and removing defects or errors in source code.",
        emojis: ["🪲", "🔍", "🛠️"],
        answer: "Debugging",
        options: ["Unit Testing", "Refactoring", "Compiling", "Debugging"],
        successMsg: "BUG ISOLATED & PURGED ✓",
      },
      {
        id: "m2q7",
        prompt: "Decrypt this transmission:",
        hint: "The developer platform represented by the famous Octocat mascot.",
        emojis: ["🐙", "🐱", "📁"],
        answer: "GitHub",
        options: ["GitLab", "GitHub", "Bitbucket", "DockerHub"],
        successMsg: "GITHUB REPO CLONED ✓",
      },
      {
        id: "m2q8",
        prompt: "Decrypt this transmission:",
        hint: "Simulation of human intelligence by computer systems and algorithms.",
        emojis: ["🧠", "🤖", "⚡"],
        answer: "Artificial Intelligence (AI)",
        options: ["Artificial Intelligence (AI)", "Quantum Computing", "Robotic Process Automation", "Distributed Systems"],
        successMsg: "AI NEURAL LINK ONLINE ✓",
      },
      {
        id: "m2q9",
        prompt: "Decrypt this transmission:",
        hint: "Platform used to build, share, and run software containers.",
        emojis: ["🐳", "📦", "🚢"],
        answer: "Docker",
        options: ["Kubernetes", "Terraform", "Docker", "Vagrant"],
        successMsg: "DOCKER CONTAINER DEPLOYED ✓",
      },
      {
        id: "m2q10",
        prompt: "Decrypt this transmission:",
        hint: "A specific type of malicious software designed to gather data about a user without consent.",
        emojis: ["🕵️", "🖥️", "🦠"],
        answer: "Spyware",
        options: ["Ransomware", "Adware", "Spyware", "Trojan Horse"],
        successMsg: "SPYWARE DETECTED & NEUTRALIZED ✓",
      },
      {
        id: "m2q11",
        prompt: "Decrypt this transmission:",
        hint: "Small blocks of data created by a web server and placed on a device while browsing.",
        emojis: ["🍪", "🌐", "📄"],
        answer: "Browser Cookies",
        options: ["Browser Cookies", "Web Sockets", "Session Tokens", "IndexedDB"],
        successMsg: "BROWSER COOKIE DECODED ✓",
      },
      {
        id: "m2q12",
        prompt: "Decrypt this transmission:",
        hint: "Automated bots sent by search engines like Google to index website pages across the web.",
        emojis: ["🕸️", "🕷️", "🔍"],
        answer: "Web Crawlers / Spiders",
        options: ["Web Scraping Scripts", "Web Crawlers / Spiders", "RSS Aggregators", "Packet Sniffers"],
        successMsg: "WEB SPIDER TRAIL INDEXED ✓",
      },
      {
        id: "m2q13",
        prompt: "Decrypt this transmission:",
        hint: "Transforming readable plain text into unreadable ciphertext to prevent eavesdropping.",
        emojis: ["🔒", "🔑", "🛡️"],
        answer: "Encryption",
        options: ["Serialization", "Compression", "Hashing", "Encryption"],
        successMsg: "CIPHER DECRYPTED ✓",
      },
      {
        id: "m2q14",
        prompt: "Decrypt this transmission:",
        hint: "Social engineering attack where deceptive emails trick people into revealing sensitive info.",
        emojis: ["🐟", "🎣", "📧"],
        answer: "Phishing",
        options: ["Phishing", "Spoofing", "DDOS", "Man-in-the-Middle"],
        successMsg: "PHISHING VECTOR BLOCKED ✓",
      },
      {
        id: "m2q15",
        prompt: "Decrypt this transmission:",
        hint: "The free, open-source UNIX-like operating system kernel created by Linus Torvalds.",
        emojis: ["🐧", "🖥️", "🆓"],
        answer: "Linux",
        options: ["FreeBSD", "Linux", "macOS", "Windows Subsystem"],
        successMsg: "LINUX ROOT ACCESS GRANTED ✓",
      },
    ],
  },

  // ─── MODULE 3: UNSCRAMBLE ─────────────────────────────────────────────────────
  {
    id: 3,
    title: "UNSCRAMBLE",
    subtitle: "Data packets scrambled. Reassemble the corrupted files.",
    icon: "🔤",
    type: "unscramble",
    color: "#39ff14",
    questions: [
      {
        id: "m3q1",
        title: "Firewall",
        prompt: "Reconstruct the corrupted cybersecurity term:",
        scrambled: ["R", "E", "F", "W", "I", "A", "L", "L"],
        answer: "FIREWALL",
        hint: "🧱 Network barrier that blocks unauthorized traffic",
        successMsg: "FIREWALL RESTORED ✓",
      },
      {
        id: "m3q2",
        title: "Binary",
        prompt: "Reconstruct the corrupted computational numbering term:",
        scrambled: ["N", "I", "B", "A", "R", "Y"],
        answer: "BINARY",
        hint: "0️⃣ Base-2 numbering system made of 0s and 1s",
        successMsg: "BINARY LOGIC RESTORED ✓",
      },
      {
        id: "m3q3",
        title: "Cache",
        prompt: "Reconstruct the corrupted hardware memory term:",
        scrambled: ["C", "A", "H", "C", "E"],
        answer: "CACHE",
        hint: "⚡ High-speed temporary memory for quick data access",
        successMsg: "CACHE BUFFER RESTORED ✓",
      },
      {
        id: "m3q4",
        title: "Bandwidth",
        prompt: "Reconstruct the corrupted network throughput term:",
        scrambled: ["B", "A", "N", "D", "W", "I", "D", "T", "H"],
        answer: "BANDWIDTH",
        hint: "🌐 Maximum rate of data transfer across a network",
        successMsg: "BANDWIDTH RESTORED ✓",
      },
      {
        id: "m3q5",
        title: "Debugging",
        prompt: "Reconstruct the corrupted software development term:",
        scrambled: ["B", "E", "G", "U", "D", "G", "I", "N", "G"],
        answer: "DEBUGGING",
        hint: "🪲 Finding and resolving errors in source code",
        successMsg: "CODE CLEANSED ✓",
      },
      {
        id: "m3q6",
        title: "Firmware",
        prompt: "Reconstruct the corrupted embedded software term:",
        scrambled: ["F", "I", "R", "M", "W", "A", "R", "E"],
        answer: "FIRMWARE",
        hint: "💾 Permanent software programmed into read-only memory",
        successMsg: "FIRMWARE FLASHED ✓",
      },
      {
        id: "m3q7",
        title: "Hashing",
        prompt: "Reconstruct the corrupted cryptography term:",
        scrambled: ["H", "A", "S", "H", "I", "N", "G"],
        answer: "HASHING",
        hint: "🔑 Converting data into a fixed-length string of characters",
        successMsg: "HASH DIGEST VERIFIED ✓",
      },
      {
        id: "m3q8",
        title: "Repository",
        prompt: "Reconstruct the corrupted version control storage term:",
        scrambled: ["R", "E", "P", "O", "S", "I", "T", "O", "R", "Y"],
        answer: "REPOSITORY",
        hint: "📂 Storage location for code, commits, and assets (Git)",
        successMsg: "REPO RECOVERED ✓",
      },
      {
        id: "m3q9",
        title: "Backup",
        prompt: "Reconstruct the corrupted data protection term:",
        scrambled: ["B", "A", "C", "K", "U", "P"],
        answer: "BACKUP",
        hint: "💽 Duplicate copy of data kept safe in case of loss",
        successMsg: "SNAPSHOT RESTORED ✓",
      },
      {
        id: "m3q10",
        title: "Virtual",
        prompt: "Reconstruct the corrupted simulation & cloud term:",
        scrambled: ["V", "I", "R", "T", "U", "A", "L"],
        answer: "VIRTUAL",
        hint: "🥽 Simulated digital environment or machine instance",
        successMsg: "INSTANCE INITIALIZED ✓",
      },
      {
        id: "m3q11",
        title: "Kernel",
        prompt: "Reconstruct the corrupted OS architecture term:",
        scrambled: ["K", "E", "R", "N", "E", "L"],
        answer: "KERNEL",
        hint: "🧠 Core component of an OS that manages hardware & processes",
        successMsg: "CORE KERNEL COMPILED ✓",
      },
      {
        id: "m3q12",
        title: "Packet",
        prompt: "Reconstruct the corrupted network routing term:",
        scrambled: ["P", "A", "C", "K", "E", "T"],
        answer: "PACKET",
        hint: "📦 Small unit of data routed over a network",
        successMsg: "DATA PACKET ROUTED ✓",
      },
      {
        id: "m3q13",
        title: "Server",
        prompt: "Reconstruct the corrupted network infrastructure term:",
        scrambled: ["S", "E", "R", "V", "E", "R"],
        answer: "SERVER",
        hint: "🖥️ Computer providing services or data to other clients",
        successMsg: "SERVER RESPONSIVE ✓",
      },
      {
        id: "m3q14",
        title: "Malware",
        prompt: "Reconstruct the corrupted cybersecurity threat term:",
        scrambled: ["M", "A", "L", "W", "A", "R", "E"],
        answer: "MALWARE",
        hint: "🦠 Hostile, intrusive, or malicious software",
        successMsg: "THREAT QUARANTINED ✓",
      },
      {
        id: "m3q15",
        title: "Browser",
        prompt: "Reconstruct the corrupted web client application term:",
        scrambled: ["B", "R", "O", "W", "S", "E", "R"],
        answer: "BROWSER",
        hint: "🌍 Application used to access and view the World Wide Web",
        successMsg: "BROWSER ENGINE RESTORED ✓",
      },
    ],
  },

  // ─── MODULE 4: ODD ONE OUT ───────────────────────────────────────────────────
  {
    id: 4,
    title: "ODD ONE OUT",
    subtitle: "Intruder detected in the system. Eliminate it before time runs out.",
    icon: "👀",
    type: "odd_one_out",
    color: "#ff2a2a",
    timePerQuestion: 8, // seconds
    questions: [
      {
        id: "m4q1",
        title: "Processing vs Memory",
        prompt: "Identify the rogue component in this hardware cluster:",
        items: ["CPU", "GPU", "ALU", "RAM"],
        answer: "RAM",
        hint: "💾 Memory vs Processor",
        explanation: "RAM is primary volatile memory, while CPU, GPU, and ALU are processing components.",
        successMsg: "INTRUDER ELIMINATED ✓",
      },
      {
        id: "m4q2",
        title: "Web Stack vs Scripting",
        prompt: "Identify the language running outside the browser engine:",
        items: ["HTML", "CSS", "JavaScript", "Python"],
        answer: "Python",
        hint: "🐍 Browser vs Backend",
        explanation: "Python is primarily a backend/scientific language, while HTML, CSS, and JS form the core browser stack.",
        successMsg: "ANOMALOUS STACK PURGED ✓",
      },
      {
        id: "m4q3",
        title: "Browsers vs OS",
        prompt: "Identify the foreign software architecture in this lineup:",
        items: ["Chrome", "Firefox", "Edge", "Linux"],
        answer: "Linux",
        hint: "🐧 Browser vs Kernel",
        explanation: "Linux is an operating system kernel, whereas Chrome, Firefox, and Edge are web browsers.",
        successMsg: "ROGUE KERNEL ISOLATED ✓",
      },
      {
        id: "m4q4",
        title: "Protocols vs Media",
        prompt: "Identify the packet that is not a transmission protocol:",
        items: ["TCP", "UDP", "HTTP", "JPEG"],
        answer: "JPEG",
        hint: "🖼️ Network vs Image",
        explanation: "JPEG is an image file format, while TCP, UDP, and HTTP are network transfer protocols.",
        successMsg: "INTRUDER ELIMINATED ✓",
      },
      {
        id: "m4q5",
        title: "OS vs Database",
        prompt: "Identify the software entity that is not an operating system:",
        items: ["Windows", "Linux", "macOS", "MySQL"],
        answer: "MySQL",
        hint: "🐬 Platform vs Database",
        explanation: "MySQL is a relational database engine, while Windows, Linux, and macOS are operating systems.",
        successMsg: "DATABASE ENGINE NEUTRALIZED ✓",
      },
      {
        id: "m4q6",
        title: "Input vs Output",
        prompt: "Identify the peripheral that breaks the input stream:",
        items: ["Keyboard", "Mouse", "Scanner", "Monitor"],
        answer: "Monitor",
        hint: "🖥️ Input vs Output",
        explanation: "Monitor is a visual output device, whereas Keyboard, Mouse, and Scanner are input peripherals.",
        successMsg: "OUTPUT DEVICE QUARANTINED ✓",
      },
      {
        id: "m4q7",
        title: "Storage vs Circuit Board",
        prompt: "Identify the hardware component that does not store data directly:",
        items: ["SSD", "Hard Disk", "Flash Drive", "Motherboard"],
        answer: "Motherboard",
        hint: "🧩 Storage vs Mainboard",
        explanation: "Motherboard is the main system circuit board, while SSD, Hard Disk, and Flash Drive are storage media.",
        successMsg: "HARDWARE ANOMALY PURGED ✓",
      },
      {
        id: "m4q8",
        title: "Wireless vs Wired",
        prompt: "Identify the transmission channel that relies on physical copper:",
        items: ["Bluetooth", "Wi-Fi", "Zigbee", "Ethernet Cable"],
        answer: "Ethernet Cable",
        hint: "🔌 Wireless vs Wired",
        explanation: "Ethernet Cable is a physical wired line, while Bluetooth, Wi-Fi, and Zigbee are wireless RF protocols.",
        successMsg: "PHYSICAL TAP DETECTED & CUT ✓",
      },
      {
        id: "m4q9",
        title: "Containers vs Graphic Suite",
        prompt: "Identify the rogue process in the DevOps container cluster:",
        items: ["Docker", "Kubernetes", "Podman", "Photoshop"],
        answer: "Photoshop",
        hint: "🎨 DevOps vs Graphics",
        explanation: "Photoshop is creative design software, whereas Docker, Kubernetes, and Podman are container systems.",
        successMsg: "UNAUTHORIZED APP TERMINATED ✓",
      },
      {
        id: "m4q10",
        title: "VCS vs Web Server",
        prompt: "Identify the tool that is not a Version Control System:",
        items: ["Git", "SVN", "Mercurial", "Apache"],
        answer: "Apache",
        hint: "🪶 Source Code vs Web Server",
        explanation: "Apache is an HTTP web server, while Git, SVN, and Mercurial are version control systems.",
        successMsg: "DAEMON DISCONNECTED ✓",
      },
      {
        id: "m4q11",
        title: "Hardware vs Compiler",
        prompt: "Identify the digital artifact that is purely software:",
        items: ["Router", "Switch", "Hub", "Compiler"],
        answer: "Compiler",
        hint: "⚙️ Physical Gear vs Software",
        explanation: "Compiler is software code translation tooling, whereas Router, Switch, and Hub are physical network hardware.",
        successMsg: "ROGUE BINARY REMOVED ✓",
      },
      {
        id: "m4q12",
        title: "Mobile OS vs Enterprise Entity",
        prompt: "Identify the entity that is not a mobile operating system:",
        items: ["Android", "iOS", "Windows Phone", "Oracle"],
        answer: "Oracle",
        hint: "🏛️ Mobile OS vs Enterprise Software",
        explanation: "Oracle is an enterprise database corporation, while Android, iOS, and Windows Phone are mobile OS platforms.",
        successMsg: "CORPORATE INTRUDER EJECTED ✓",
      },
      {
        id: "m4q13",
        title: "Audio vs Document Format",
        prompt: "Identify the file format that does not transmit sonic waveforms:",
        items: ["MP3", "WAV", "FLAC", "PDF"],
        answer: "PDF",
        hint: "📄 Sound vs Document",
        explanation: "PDF is a page layout document format, whereas MP3, WAV, and FLAC are digital audio formats.",
        successMsg: "NON-AUDIO STREAM PURGED ✓",
      },
      {
        id: "m4q14",
        title: "Code vs Hardware Interface",
        prompt: "Identify the item that is a physical connector cable rather than code:",
        items: ["C++", "Rust", "Go", "HDMI"],
        answer: "HDMI",
        hint: "📺 Programming vs Video Interface",
        explanation: "HDMI is an audio/video display interface cable, while C++, Rust, and Go are compiled programming languages.",
        successMsg: "CABLE EXPLOIT UNPLUGGED ✓",
      },
      {
        id: "m4q15",
        title: "Security Stack vs Office Tool",
        prompt: "Identify the application that does not defend the infrastructure:",
        items: ["Firewall", "Antivirus", "VPN", "Excel"],
        answer: "Excel",
        hint: "📊 Cybersecurity vs Spreadsheet",
        explanation: "Excel is a spreadsheet office app, while Firewall, Antivirus, and VPN are computer security tools.",
        successMsg: "PRODUCTIVITY SPREADSHEET PURGED ✓",
      },
    ],
  },

  // ─── MODULE 5: TECH RIDDLE ───────────────────────────────────────────────────
  {
    id: 5,
    title: "TECH RIDDLE",
    subtitle: "Security checkpoint. The system demands identification.",
    icon: "🧠",
    type: "tech_riddle",
    color: "#00f0ff",
    questions: [
      {
        id: "m5q1",
        title: "The Programmer's Confusion",
        prompt: "> I speak without a mouth,\n> I understand without a brain.\n> You give me instructions,\n> But I sometimes do the opposite of what you want.\n> One missing symbol,\n> And your entire day is ruined.\n\nIDENTIFY ME.",
        answer: "Programming Language / Compiler",
        options: ["Computer Mouse", "Programming Language / Compiler", "Keyboard", "Database"],
        successMsg: "SYNTAX RESOLVED ✓",
      },
      {
        id: "m5q2",
        title: "The Copy-Paste Genius",
        prompt: "> I can write your entire assignment,\n> But I don't understand a single word.\n> I can solve your problems,\n> But I might create three new ones.\n> Everyone uses me,\n> But nobody wants the teacher to know.\n\nIDENTIFY ME.",
        answer: "ChatGPT / AI",
        options: ["Google", "Calculator", "ChatGPT / AI", "Compiler"],
        successMsg: "INTELLIGENCE ISOLATED ✓",
      },
      {
        id: "m5q3",
        title: "The Programmer's Loop",
        prompt: "> I repeat what you tell me.\n> I never get bored.\n> I continue until you tell me to stop.\n> But if you forget to tell me when to stop,\n> We both have a very long day.\n\nIDENTIFY ME.",
        answer: "Loop",
        options: ["Variable", "Loop", "Function", "Compiler"],
        successMsg: "CYCLE TERMINATED ✓",
      },
      {
        id: "m5q4",
        title: "The Memory Thief",
        prompt: "> I remember things temporarily.\n> I am faster than your phone's storage.\n> When the power goes off,\n> I forget almost everything.\n\nIDENTIFY ME.",
        answer: "RAM",
        options: ["RAM", "SSD", "ROM", "Hard Disk"],
        successMsg: "VOLATILE MEMORY IDENTIFIED ✓",
      },
      {
        id: "m5q5",
        title: "The Hostel Hero",
        prompt: "> I am invisible,\n> but everyone searches for me.\n> When I am strong, everyone is happy.\n> When I am weak, everyone becomes an engineer.\n> When I disappear,\n> the entire hostel comes downstairs.\n\nIDENTIFY ME.",
        answer: "Wi-Fi",
        options: ["Electricity", "Wi-Fi", "Bluetooth", "Mobile Battery"],
        successMsg: "SIGNAL RESTORED ✓",
      },
      {
        id: "m5q6",
        title: "The Password Problem",
        prompt: "> I protect your Instagram,\n> your Gmail, and your bank account.\n> Everyone wants to know me,\n> but if someone guesses me, you're in trouble.\n> And if YOU forget me,\n> you're in even bigger trouble.\n\nIDENTIFY ME.",
        answer: "Password",
        options: ["Username", "OTP", "Password", "Email"],
        successMsg: "CREDENTIALS VERIFIED ✓",
      },
      {
        id: "m5q7",
        title: "The Silent Storage",
        prompt: "> I keep your photos, videos and files.\n> I don't forget them when you turn the computer off.\n> I am slower than RAM,\n> but I remember things for much longer.\n\nIDENTIFY ME.",
        answer: "Storage",
        options: ["RAM", "CPU", "Storage", "Cache"],
        successMsg: "DATA PERSISTENCE CONFIRMED ✓",
      },
      {
        id: "m5q8",
        title: "The Brain of the Computer",
        prompt: "> I don't have a brain,\n> but people call me one.\n> I perform calculations,\n> follow instructions,\n> and work extremely fast.\n\nIDENTIFY ME.",
        answer: "CPU",
        options: ["CPU", "Monitor", "Keyboard", "Router"],
        successMsg: "PROCESSING CORE LOCATED ✓",
      },
      {
        id: "m5q9",
        title: "The Internet Gatekeeper",
        prompt: "> I stand between you and the internet.\n> I send your requests where they need to go.\n> Without me, connecting multiple devices\n> would become much harder.\n\nIDENTIFY ME.",
        answer: "Router",
        options: ["Router", "Printer", "Monitor", "Scanner"],
        successMsg: "GATEWAY UNLOCKED ✓",
      },
      {
        id: "m5q10",
        title: "The Invisible Messenger",
        prompt: "> You cannot see me,\n> but I can carry information through the air.\n> I connect your phone to your headphones\n> without using a wire.\n\nIDENTIFY ME.",
        answer: "Bluetooth",
        options: ["HDMI", "Bluetooth", "Ethernet Cable", "USB"],
        successMsg: "WIRELESS LINK PAIRED ✓",
      },
      {
        id: "m5q11",
        title: "The Web Address",
        prompt: "> You type me into a browser\n> when you want to visit a website.\n> I tell the browser where to go.\n\nIDENTIFY ME.",
        answer: "URL",
        options: ["URL", "RAM", "CPU", "Firewall"],
        successMsg: "DESTINATION RESOLVED ✓",
      },
      {
        id: "m5q12",
        title: "The Digital Door",
        prompt: "> I protect your computer from unwanted visitors.\n> I check what enters and leaves your network.\n> If something looks dangerous,\n> I can block it before it gets inside.\n\nIDENTIFY ME.",
        answer: "Firewall",
        options: ["Firewall", "Browser", "Keyboard", "Compiler"],
        successMsg: "DEFENSE GRID ACTIVE ✓",
      },
      {
        id: "m5q13",
        title: "The Search Expert",
        prompt: "> You ask me a question,\n> and I search through millions of pages to find an answer.\n> I don't go to college,\n> but somehow I know where everything is.\n\nIDENTIFY ME.",
        answer: "Search Engine",
        options: ["Search Engine", "Operating System", "CPU", "Firewall"],
        successMsg: "INDEX LOCATED ✓",
      },
      {
        id: "m5q14",
        title: "The Digital Translator",
        prompt: "> You write instructions in a language humans understand.\n> I help the computer understand those instructions.\n> Without me, your program may never run.\n\nIDENTIFY ME.",
        answer: "Compiler",
        options: ["Compiler", "Monitor", "Router", "RAM"],
        successMsg: "BINARY COMPILED ✓",
      },
      {
        id: "m5q15",
        title: "The Multitasker",
        prompt: "> I can have many programs running at once.\n> I manage your files, memory and applications.\n> You interact with me every time you use your computer.\n\nIDENTIFY ME.",
        answer: "Operating System",
        options: ["Operating System", "Keyboard", "CPU Fan", "Browser"],
        successMsg: "KERNEL SYNCHRONIZED ✓",
      },
    ],
  },

  // ─── MODULE 6: TECH SEQUENCE ─────────────────────────────────────────────────
  {
    id: 6,
    title: "TECH SEQUENCE",
    subtitle: "Corrupted pipeline stream detected. Restore the correct operational order.",
    icon: "🔢",
    type: "tech_sequence",
    color: "#ff00aa",
    questions: [
      {
        id: "m6q1",
        title: "Connecting to Wi-Fi",
        prompt: "Reconstruct the correct operational execution order for: CONNECTING TO WI-FI",
        items: ["Enter Password", "Turn on Wi-Fi", "Connected", "Select Network Name (SSID)"],
        correctOrder: ["Turn on Wi-Fi", "Select Network Name (SSID)", "Enter Password", "Connected"],
        successMsg: "NETWORK CONNECTION ESTABLISHED ✓",
      },
      {
        id: "m6q2",
        title: "Software Bug Lifecycle",
        prompt: "Reconstruct the correct operational execution order for: SOFTWARE BUG LIFECYCLE",
        items: ["QA Retest", "Issue Fixed", "Bug Reported", "Code Patch Written"],
        correctOrder: ["Bug Reported", "Code Patch Written", "Issue Fixed", "QA Retest"],
        successMsg: "BUG LIFECYCLE RESOLVED ✓",
      },
      {
        id: "m6q3",
        title: "Installing a Desktop Application",
        prompt: "Reconstruct the correct operational execution order for: INSTALLING A DESKTOP APPLICATION",
        items: ["Run Installer", "Download Setup File", "Accept License Terms", "Finish & Launch"],
        correctOrder: ["Download Setup File", "Run Installer", "Accept License Terms", "Finish & Launch"],
        successMsg: "APPLICATION DEPLOYED ✓",
      },
      {
        id: "m6q4",
        title: "Machine Learning Pipeline",
        prompt: "Reconstruct the correct operational execution order for: MACHINE LEARNING PIPELINE",
        items: ["Make Predictions", "Collect Data", "Model Training", "Feature Engineering / Cleaning"],
        correctOrder: ["Collect Data", "Feature Engineering / Cleaning", "Model Training", "Make Predictions"],
        successMsg: "MODEL PIPELINE CONVERGED ✓",
      },
      {
        id: "m6q5",
        title: "Git Version Control Workflow",
        prompt: "Reconstruct the correct operational execution order for: GIT VERSION CONTROL WORKFLOW",
        items: ["git push", "git commit", "Edit Files", "git add"],
        correctOrder: ["Edit Files", "git add", "git commit", "git push"],
        successMsg: "COMMIT TREE SYNCHRONIZED ✓",
      },
      {
        id: "m6q6",
        title: "CPU Instruction Execution (Machine Cycle)",
        prompt: "Reconstruct the correct operational execution order for: CPU INSTRUCTION EXECUTION",
        items: ["Store Result", "Decode", "Fetch Instruction", "Execute"],
        correctOrder: ["Fetch Instruction", "Decode", "Execute", "Store Result"],
        successMsg: "INSTRUCTION CYCLE RESTORED ✓",
      },
      {
        id: "m6q7",
        title: "Resolving a Domain Name (DNS Lookup)",
        prompt: "Reconstruct the correct operational execution order for: RESOLVING A DOMAIN NAME",
        items: ["IP Address Returned", "Query Root Server", "Enter Web Domain", "Query TLD Server"],
        correctOrder: ["Enter Web Domain", "Query Root Server", "Query TLD Server", "IP Address Returned"],
        successMsg: "DNS RESOLUTION VERIFIED ✓",
      },
      {
        id: "m6q8",
        title: "Biometric Smartphone Unlock",
        prompt: "Reconstruct the correct operational execution order for: BIOMETRIC SMARTPHONE UNLOCK",
        items: ["Match Found", "Finger Touches Sensor", "Home Screen Displays", "Hash Verification"],
        correctOrder: ["Finger Touches Sensor", "Hash Verification", "Match Found", "Home Screen Displays"],
        successMsg: "BIOMETRIC MATCH CONFIRMED ✓",
      },
      {
        id: "m6q9",
        title: "Online Payment Gateway (UPI / Card)",
        prompt: "Reconstruct the correct operational execution order for: ONLINE PAYMENT GATEWAY",
        items: ["Merchant Confirmation", "Enter PIN / OTP", "Bank Authorization", "Checkout Click"],
        correctOrder: ["Checkout Click", "Enter PIN / OTP", "Bank Authorization", "Merchant Confirmation"],
        successMsg: "TRANSACTION AUTHORIZED ✓",
      },
      {
        id: "m6q10",
        title: "3D Printing an Object",
        prompt: "Reconstruct the correct operational execution order for: 3D PRINTING AN OBJECT",
        items: ["Slice into Layers (G-Code)", "3D Model Design (CAD)", "Post-Processing/Removal", "Extrusion & Print"],
        correctOrder: ["3D Model Design (CAD)", "Slice into Layers (G-Code)", "Extrusion & Print", "Post-Processing/Removal"],
        successMsg: "FABRICATION SEQUENCE ALIGNED ✓",
      },
      {
        id: "m6q11",
        title: "Over-The-Air (OTA) Phone Update",
        prompt: "Reconstruct the correct operational execution order for: OVER-THE-AIR (OTA) PHONE UPDATE",
        items: ["System Reboot", "Verification Check", "Update Available Notification", "Download Package"],
        correctOrder: ["Update Available Notification", "Download Package", "Verification Check", "System Reboot"],
        successMsg: "FIRMWARE UPDATE PATCHED ✓",
      },
      {
        id: "m6q12",
        title: "Streaming an Online Video",
        prompt: "Reconstruct the correct operational execution order for: STREAMING AN ONLINE VIDEO",
        items: ["Buffer Video Chunks", "Video Playback", "Click Play", "Server Request Sent"],
        correctOrder: ["Click Play", "Server Request Sent", "Buffer Video Chunks", "Video Playback"],
        successMsg: "MEDIA STREAM BUFFERED ✓",
      },
      {
        id: "m6q13",
        title: "Bluetooth Audio Pairing",
        prompt: "Reconstruct the correct operational execution order for: BLUETOOTH AUDIO PAIRING",
        items: ["Device Discovered", "Enable Pairing Mode", "Audio Connected", "Tap Device Name"],
        correctOrder: ["Enable Pairing Mode", "Device Discovered", "Tap Device Name", "Audio Connected"],
        successMsg: "PERIPHERAL PAIRED ✓",
      },
      {
        id: "m6q14",
        title: "Relational Database Query (SQL Execution)",
        prompt: "Reconstruct the correct operational execution order for: RELATIONAL DATABASE QUERY",
        items: ["Fetch Records", "Query Optimization", "Write SQL Query", "Parsing / Syntax Check"],
        correctOrder: ["Write SQL Query", "Parsing / Syntax Check", "Query Optimization", "Fetch Records"],
        successMsg: "QUERY PLAN EXECUTED ✓",
      },
      {
        id: "m6q15",
        title: "Continuous Integration / Deployment (CI/CD)",
        prompt: "Reconstruct the correct operational execution order for: CI/CD PIPELINE DEPLOYMENT",
        items: ["Automated Test Suite", "Production Deploy", "Pull Request Created", "Build Artifact Generation"],
        correctOrder: ["Pull Request Created", "Build Artifact Generation", "Automated Test Suite", "Production Deploy"],
        successMsg: "DEPLOYMENT PIPELINE VERIFIED ✓",
      },
    ],
  },

  // ─── MODULE 7: GUESS THE TECHNOLOGY ─────────────────────────────────────────
  {
    id: 7,
    title: "GUESS THE TECHNOLOGY",
    subtitle: "Visual investigation. Analyze the cropped visual evidence and clues to identify the technology.",
    icon: "💻",
    type: "guess_technology",
    color: "#39ff14",
    questions: [
      {
        id: "m7q1",
        title: "NVIDIA",
        prompt: "Identify the tech giant from this visual crop & evidence:",
        hint: "🟢 The GPU powerhouse behind modern AI acceleration and PC gaming",
        cropArea: "Extreme close-up of the bright neon green curved spiral eye",
        image: "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=800&auto=format&fit=crop&q=80",
        clues: [
          "Extreme close-up of the bright neon green curved spiral eye.",
          "The undisputed hardware powerhouse fueling modern LLMs and generative AI.",
          "Maker of GeForce RTX and CUDA acceleration architecture.",
        ],
        answer: "NVIDIA",
        options: ["Intel", "NVIDIA", "AMD", "Qualcomm"],
        successMsg: "HARDWARE TITAN IDENTIFIED ✓",
      },
      {
        id: "m7q2",
        title: "Snapchat",
        prompt: "Identify the social platform from this visual crop & evidence:",
        hint: "👻 Ephemeral messaging platform famous for stories, streaks, and lenses",
        cropArea: "The bottom curve of the white ghost outline against pure bright yellow",
        image: "https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?w=800&auto=format&fit=crop&q=80",
        clues: [
          "The bottom curve of a white silhouette ghost over vivid canary yellow.",
          "Pioneered disappearing photos, Snap Map, and facial AR lenses.",
          "Founded by Evan Spiegel and Bobby Murphy under Snap Inc.",
        ],
        answer: "Snapchat",
        options: ["TikTok", "Snapchat", "Instagram", "BeReal"],
        successMsg: "PLATFORM CLASSIFIED ✓",
      },
      {
        id: "m7q3",
        title: "OpenAI / ChatGPT",
        prompt: "Identify the AI laboratory from this visual crop & evidence:",
        hint: "🤖 Generative AI pioneer behind GPT models and conversational assistants",
        cropArea: "A single quadrant of the interlocking geometric teal/green rosette",
        image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&auto=format&fit=crop&q=80",
        clues: [
          "A single quadrant of the interlocking geometric green/teal rosette spiral.",
          "Creator of ChatGPT, GPT-4o, DALL-E, and Sora.",
          "Founded in San Francisco as an AI research lab.",
        ],
        answer: "OpenAI / ChatGPT",
        options: ["Anthropic", "OpenAI / ChatGPT", "DeepMind", "Mistral AI"],
        successMsg: "SYNTHETIC INTELLIGENCE DETECTED ✓",
      },
      {
        id: "m7q4",
        title: "Xbox (Microsoft)",
        prompt: "Identify the gaming ecosystem from this visual crop & evidence:",
        hint: "🎮 Home gaming console ecosystem featuring Game Pass",
        cropArea: "Top curve of the embossed metallic 3D sphere with an illuminated green 'X'",
        image: "https://images.unsplash.com/photo-1605901309584-818e25960a8f?w=800&auto=format&fit=crop&q=80",
        clues: [
          "Top curve of the embossed metallic sphere with an illuminated neon green 'X'.",
          "Flagship gaming brand of Microsoft featuring Game Pass and Series X.",
          "Home to franchises like Halo, Gears of War, and Forza.",
        ],
        answer: "Xbox",
        options: ["PlayStation", "Xbox", "Nintendo", "Steam Deck"],
        successMsg: "CONSOLE ECOSYSTEM IDENTIFIED ✓",
      },
      {
        id: "m7q5",
        title: "Discord",
        prompt: "Identify the communication network from this visual crop & evidence:",
        hint: "🎧 The community chat platform known for servers, voice channels, and 'Clyde'",
        cropArea: "One white controller handle and purple circular eye on blurple backdrop",
        image: "https://images.unsplash.com/photo-1614680376593-902f749f7ffc?w=800&auto=format&fit=crop&q=80",
        clues: [
          "One white controller handle and circular eye on a distinctive 'blurple' field.",
          "The hub for gaming communities, voice channels, stages, and bots.",
          "Its friendly controller mascot is officially named 'Clyde'.",
        ],
        answer: "Discord",
        options: ["Slack", "Discord", "Telegram", "Teams"],
        successMsg: "COMM CHANNEL DECRYPTED ✓",
      },
      {
        id: "m7q6",
        title: "GitHub",
        prompt: "Identify the developer platform from this visual crop & evidence:",
        hint: "🐙 The world's largest host of source code repositories and version control",
        cropArea: "Close-up of the silhouette cat ears or tentacles of the Octocat",
        image: "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=800&auto=format&fit=crop&q=80",
        clues: [
          "Silhouette of cat ears and tentacle tails on a dark circular badge.",
          "Home to open-source pull requests, issues, Actions CI/CD, and Copilot.",
          "Its famous mascot is the feline-cephalopod hybrid 'Mona the Octocat'.",
        ],
        answer: "GitHub",
        options: ["GitLab", "GitHub", "Bitbucket", "SourceForge"],
        successMsg: "REPOSITORY NETWORK IDENTIFIED ✓",
      },
      {
        id: "m7q7",
        title: "Spotify",
        prompt: "Identify the streaming provider from this visual crop & evidence:",
        hint: "🎵 Green circular streaming service that broadcasts over 100 million audio tracks",
        cropArea: "The three curved black soundwave arcs zoomed in over neon green",
        image: "https://images.unsplash.com/photo-1614680376408-81e91ffe3db7?w=800&auto=format&fit=crop&q=80",
        clues: [
          "Three curved black soundwave broadcast arcs inside a vibrant lime-green disc.",
          "Swedish streaming juggernaut with algorithmic Discover Weekly and Wrapped.",
          "Streams over 100 million songs and millions of podcasts globally.",
        ],
        answer: "Spotify",
        options: ["Apple Music", "Spotify", "Tidal", "SoundCloud"],
        successMsg: "STREAMING PROTOCOL LOCATED ✓",
      },
      {
        id: "m7q8",
        title: "Docker",
        prompt: "Identify the virtualization technology from this visual crop & evidence:",
        hint: "🐳 Software platform for containerizing applications with OS-level virtualization",
        cropArea: "Two stacked blue cargo shipping containers on top of the whale's back",
        image: "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?w=800&auto=format&fit=crop&q=80",
        clues: [
          "Stacked blue modular cargo freight containers riding atop a blue whale.",
          "Pioneered OS-level virtualization packaging apps into portable containers.",
          "Defined by Dockerfiles, Docker Compose, and Docker Hub.",
        ],
        answer: "Docker",
        options: ["Kubernetes", "Docker", "Vagrant", "VMware"],
        successMsg: "CONTAINER RUNTIME CONFIRMED ✓",
      },
      {
        id: "m7q9",
        title: "Android (Google)",
        prompt: "Identify the mobile operating system from this visual crop & evidence:",
        hint: "🤖 Open-source mobile OS developed by Google and named after desserts",
        cropArea: "Close-up of one circular white eyeball and green antenna of the bugdroid",
        image: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&auto=format&fit=crop&q=80",
        clues: [
          "A circular white eye pupil and angled antenna of a friendly green robot head.",
          "Google's Linux-based open source operating system for mobile devices.",
          "Historically named releases after confectioneries (Cupcake, Donut, Oreo).",
        ],
        answer: "Android",
        options: ["iOS", "Android", "HarmonyOS", "KaiOS"],
        successMsg: "MOBILE SYSTEM CLASSIFIED ✓",
      },
      {
        id: "m7q10",
        title: "Python",
        prompt: "Identify the programming language from this visual crop & evidence:",
        hint: "🐍 High-level interpreted programming language widely used in AI, ML, and automation",
        cropArea: "Interlocking yellow and blue rounded snake heads with a single dot eye",
        image: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=800&auto=format&fit=crop&q=80",
        clues: [
          "Interlocking yellow and blue rounded serpentine shapes with dot eyes.",
          "Interpreted, high-level language revered for readable syntax and whitespace.",
          "Standard lingua franca of machine learning, PyTorch, and data science.",
        ],
        answer: "Python",
        options: ["Java", "Python", "Rust", "JavaScript"],
        successMsg: "LANGUAGE CORE DETECTED ✓",
      },
      {
        id: "m7q11",
        title: "Visual Studio Code",
        prompt: "Identify the developer tool from this visual crop & evidence:",
        hint: "💻 Microsoft's lightweight, open-source code editor with an extensive extension library",
        cropArea: "The right-hand blue origami ribbon fold over dark navy",
        image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop&q=80",
        clues: [
          "Right-hand origami ribbon geometric infinity wing in Microsoft azure blue.",
          "Extensible, lightweight editor built on Electron with integrated Git and terminal.",
          "By far the most popular IDE and code workspace among programmers today.",
        ],
        answer: "Visual Studio Code",
        options: ["Sublime Text", "Visual Studio Code", "Atom", "IntelliJ IDEA"],
        successMsg: "EDITOR SUITE CONFIRMED ✓",
      },
      {
        id: "m7q12",
        title: "Linux",
        prompt: "Identify the open-source kernel from this visual crop & evidence:",
        hint: "🐧 Monolithic kernel that powers the majority of cloud servers, supercomputers, and Android",
        cropArea: "The yellow flipper foot and round white belly of Tux the penguin",
        image: "https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=800&auto=format&fit=crop&q=80",
        clues: [
          "The yellow webbed flipper foot and round white belly of an adorable penguin.",
          "Monolithic open-source operating system kernel created by Linus Torvalds.",
          "Powers Android, cloud infrastructure, routers, and top supercomputers.",
        ],
        answer: "Linux",
        options: ["FreeBSD", "Linux", "Solaris", "Minix"],
        successMsg: "ROOT KERNEL RESTORED ✓",
      },
      {
        id: "m7q13",
        title: "Bluetooth",
        prompt: "Identify the wireless standard from this visual crop & evidence:",
        hint: "📶 Short-range 2.4 GHz wireless communication standard named after a Scandinavian king",
        cropArea: "The intersection point of the white Nordic bindrune on royal blue background",
        image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&auto=format&fit=crop&q=80",
        clues: [
          "The geometric junction of Hagall and Bjarkan Younger Futhark Nordic runes.",
          "2.4 GHz short-range protocol connecting earphones, keyboards, and watches.",
          "Named after Danish King Harald Bluetooth who united Scandinavian tribes.",
        ],
        answer: "Bluetooth",
        options: ["Zigbee", "Bluetooth", "NFC", "UWB"],
        successMsg: "RF PROTOCOL CONFIRMED ✓",
      },
      {
        id: "m7q14",
        title: "Steam (Valve)",
        prompt: "Identify the gaming platform from this visual crop & evidence:",
        hint: "🕹️ PC digital storefront and launcher featuring community workshops and seasonal sales",
        cropArea: "The mechanical crank arm and rotating locomotive valve joint",
        image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80",
        clues: [
          "Industrial mechanical locomotive piston connecting rod and pivot joint.",
          "Valve's digital PC distribution storefront, home to massive seasonal sales.",
          "Also creator of SteamOS and the handheld Steam Deck gaming PC.",
        ],
        answer: "Steam",
        options: ["Epic Games", "Steam", "GOG", "Battle.net"],
        successMsg: "GAMING NETWORK IDENTIFIED ✓",
      },
      {
        id: "m7q15",
        title: "Wi-Fi",
        prompt: "Identify the networking alliance standard from this visual crop & evidence:",
        hint: "📡 Wireless local area networking standard certified under IEEE 802.11",
        cropArea: "Black and white yin-yang curved signal radio waves",
        image: "https://images.unsplash.com/photo-1563770660941-20978e870e26?w=800&auto=format&fit=crop&q=80",
        clues: [
          "Curving yin-yang radio signal arcs creating a unified circular badge.",
          "Governed by the Wi-Fi Alliance under the IEEE 802.11 family of standards.",
          "The invisible backbone of domestic and enterprise high-speed internet.",
        ],
        answer: "Wi-Fi",
        options: ["Cellular 5G", "Wi-Fi", "Satellite", "Ethernet"],
        successMsg: "WIRELESS MAINFRAME ONLINE ✓",
      },
    ],
  },
];

/**
 * GLITCH EVENTS — Random mini-challenges (1-2 per game)
 * Triggered after module 2 and module 5 randomly.
 */
export const GLITCH_EVENTS = [
  {
    id: "ge1",
    prompt: "⚠ SYSTEM GLITCH DETECTED — Find the corrupted symbol!",
    symbols: ["△", "△", "△", "▲", "△", "△"], // ▲ is the odd one (filled)
    answer: 3, // index
    timeLimit: 5,
  },
  {
    id: "ge2",
    prompt: "⚠ MEMORY CORRUPTION — Identify the rogue character!",
    symbols: ["0", "0", "O", "0", "0", "0"], // O (letter) vs 0 (zero)
    answer: 2,
    timeLimit: 5,
  },
];

/**
 * GAME CONFIG — Tweak these values without touching game logic
 */
export const CONFIG = {
  TOTAL_TIME: 300,          // 5 minutes in seconds
  BASE_POINTS: 10,          // points per correct answer
  COMBO_THRESHOLDS: [1, 2, 3, 5], // multiplier at each level (×1, ×2, ×3, ×5)
  GLITCH_BONUS: 5,          // bonus points for catching a glitch event
  ODD_ONE_OUT_TIMER: 8,     // per-question timer for module 4
  MAX_LIVES: 3,             // starting lives
  BOOT_LINES: [             // terminal boot animation lines
    "> Initializing GLITCH_MATRIX v2.4.7...",
    "> Loading kernel modules... [OK]",
    "> Scanning memory banks... CORRUPTION DETECTED",
    "> 7 modules compromised. Initiating repair protocol...",
    "> Assigning operative credentials...",
    "> Neural interface established.",
    "> JACK IN SUCCESSFUL. BEGIN REPAIR.",
  ],
};
